# 17-10-22

# 18-10-22

In [ ]:
#unpacking tuples
std1 = [(1,2,3),("nik",2,3)]
for i in std1:
    for j in len(i):
        prin

In [10]:
d = {"id":[1,2,3,4],"Name":['john','peter','ram','arun'],"salary":(1000,2004,4008,567)}

In [14]:
for i,j in d.items():
    if j.count("ram")==0:
        continue
    else:
        x = j.index("ram")
for i,j in d.items():
    print(j[x])
    

3
ram
4008


In [15]:
# shallow copy - addresses are copied , not actual values
a = [10,20,30]
b = a
b.append(40)
print(b)
print(a)


[10, 20, 30, 40]
[10, 20, 30, 40]


In [16]:
# deep copy - values will be copied
a = [30,50,60]
b = a[:]
b.append(80)
print(b)
print(a)

[30, 50, 60, 80]
[30, 50, 60]


In [ ]:
# list comprehension
[i*i if i%2==0 else i*i*i for i in range(10)]

In [24]:
def greet(sub="m"):
    '''This function prints the sub 3 times''' # shpuld be written in the first only
    print(sub*3)
greet("g")
greet()
greet.__doc__ # used to give description abt the func

ggg
mmm


'This function prints the sub 3 times'

In [25]:
isinstance(12.5,int)

False

In [ ]:
# filter function - is to filter out the elements that are satisfying the condition

In [5]:
def m(l):
    for i in range(len(l)-1):
        for j in range(len(l)-1-i):
            if l[j]<l[j+1]:
                swap = l[j+1]
                l[j+1]=l[j]
                l[j]=swap
    return l[len(l)-1]
l = [2,8,1,6,5]

print(m(l))
print(l)
    

1
[8, 6, 5, 2, 1]


In [6]:
l = [2,4,5,6]
l1 = [1,8,9,10]
l2 = list(zip(l,l1))
print(l2)

[(2, 1), (4, 8), (5, 9), (6, 10)]


In [7]:
l = [2,4,5,6]
l1 = [1,8,9,10]
l2 = dict(zip(l,l1))
print(l2)

{2: 1, 4: 8, 5: 9, 6: 10}


In [8]:
x = 20
def scope():
    global x
    print("the value of x is ",x) #2
    x = 15
    print("the value of x is ",x) #3
print("the value of x is ",x) #1
scope()

the value of x is  20
the value of x is  20
the value of x is  15


In [10]:
#lazy evaluation
def generator():
    for i in range(10):
        yield i*i
g = generator()
print(next(g))
print(next(g))

0
1


# decorators

In [15]:
# decorators
def new_decorator(actual_func):
    def wrapper_func():
        print("statement before execution of the function")
        actual_func()
        print("statement after execution of function")
    return wrapper_func

In [18]:
@new_decorator
def decorator_needed():
    print("I am not decorated yet")

In [23]:
decorator_needed()

statement before execution of the function
I am not decorated yet
statement after execution of function


In [21]:
#@new_decorator
def decorator_needed():
    print("I am not decorated yet")

In [22]:
decorator_needed()

statement before execution of the function
I am not decorated yet
statement after execution of function


In [30]:
# sys module contains all the internal python implementations
# sys.path gives all paths where python is stored
import sys
print('the command line arguments are :')
for i in sys.argv:
    print(i)
print('\n\nThe python path is',sys.path,'\n') 

the command line arguments are :
C:\Users\Nikhitha reddy\anaconda3\lib\site-packages\ipykernel_launcher.py
-f
C:\Users\Nikhitha reddy\AppData\Roaming\jupyter\runtime\kernel-7f47f91f-122d-4ff3-bb0d-ffd21ebd3d77.json


The python path is ['C:\\Users\\Nikhitha reddy\\Gemstones@JPMC', 'C:\\Users\\Nikhitha reddy\\anaconda3\\python39.zip', 'C:\\Users\\Nikhitha reddy\\anaconda3\\DLLs', 'C:\\Users\\Nikhitha reddy\\anaconda3\\lib', 'C:\\Users\\Nikhitha reddy\\anaconda3', '', 'C:\\Users\\Nikhitha reddy\\anaconda3\\lib\\site-packages', 'C:\\Users\\Nikhitha reddy\\anaconda3\\lib\\site-packages\\locket-0.2.1-py3.9.egg', 'C:\\Users\\Nikhitha reddy\\anaconda3\\lib\\site-packages\\win32', 'C:\\Users\\Nikhitha reddy\\anaconda3\\lib\\site-packages\\win32\\lib', 'C:\\Users\\Nikhitha reddy\\anaconda3\\lib\\site-packages\\Pythonwin', 'C:\\Users\\Nikhitha reddy\\anaconda3\\lib\\site-packages\\IPython\\extensions', 'C:\\Users\\Nikhitha reddy\\.ipython'] 



In [60]:
%%writefile jpc.txt
Hi, welcome to the python
Python is easy to learn

Overwriting jpc.txt


In [61]:
test = open('jpc.text','w+')

In [62]:
test.read()

''

In [63]:
test.readlines()

[]

In [64]:
test.seek(0)

0

In [65]:
#if you write like below u dont hv to close
with open('jpc.txt') as file:
    data=file.read()

In [66]:
print(data)

Hi, welcome to the python
Python is easy to learn



In [67]:
file.read() # gives error cuz file has been closed already

ValueError: I/O operation on closed file.

In [69]:
# exception handling
# try 
# except
# finally
# else
try:
    num = int(input())
    print("the result of {} is:".format(3/num2))
except ZeroDivisionError as ZD:
    print(ZD.args[0])
except ValueError as ve:
    print(ve.args[0])
except:
    print("unforeseen error")
finally:
    print("it always runs")

0
unforeseen error
it always runs


# 19-10-2022

In [1]:
import re
p = re.compile(r"a+") // r = rawstring
l = p.findall("aabcdaefgaaa")
print(l)

['aa', 'a', 'aaa']


In [2]:
import re
slist = re.findall(r"[b|B][aeiou]ll","Bill Gates and Uwe Boll \ drank Red Bull at a football match in Campbell")
print(slist)

['Bill', 'Boll', 'Bull', 'ball', 'bell']


In [3]:
class car():
    pass

In [10]:
c = car()
type(c)

__main__.car

In [5]:
c.name = "niki"


In [6]:
c.name


'niki'

In [7]:
d = car()

In [9]:
d.name = "bittu"

In [11]:
d.name

'bittu'

In [12]:
class car():
    model_name = "Honda"
    mf_year = 2008
    city ="hyd"

In [13]:
c1 = car()
c1.model_name


'Honda'

In [14]:
d1 = car()
d1.model_name

'Honda'

In [15]:
c1.mf_year = 2004

In [16]:
d1.mf_year

2008

In [17]:
class car():
    model_name = "Honda"
    mf_year = 2008
    city ="hyd"
    def trip(route):
        print("blr to hyd")

In [19]:
c = car()
c.trip()

blr to hyd


In [20]:
class emp:
    '''THis is employee database'''
    count = 0
    org = "JPMC"
    def __init__(self,Name,Salary):
        self.Name = Name
        self.Salary = Salary
        emp.count+=1
    def num_emp(self):
        print("the number of employees are: ",emp.count)
    def __repr__(self):
        return "{} {}".format(self.__class__.__name__,self.Name) # whatever you put in repr it will give in string format

In [21]:
e1 = emp("sean",2000)

In [22]:
e1.org

'JPMC'

In [23]:
e1.Name

'sean'

In [25]:
e1.num_emp()

the number of employees are:  1


In [26]:
e1.__repr__

<method-wrapper '__repr__' of emp object at 0x0000014722A7BDF0>

In [ ]:
# no method overloading in python
# latest method is taken into consideration

In [27]:
hasattr(e1,"Salary")

True

In [29]:
setattr(e1,"Salary",12000)

In [30]:
e1.Salary

12000

In [ ]:
# public , private and protected classes

In [ ]:
class car:
    def __init__(self,name,color,price):
        self.name = name
        self._color=color #private
        self.__price=price # protected

In [33]:
c1 = car("honda","red",1000)
c1.name


'honda'

In [34]:
c1._color

'red'

In [35]:
c1._car__price # for protected only thru class name we can access it

1000

In [39]:
class car:
    def __init__(self,name,speed):
        self.name = name
        self.speed = speed
    def comp(self):
        if self.speed > 100:
            print("speed is: ", self.speed)
        else :
            print("speed  is low")


In [40]:
c = car("honda",10)


In [41]:
c.comp()

speed  is low


In [43]:
class parent():
    sir_name = 'Smith'
    _city = 40
    

In [ ]:
x = parent()

In [45]:
class child(parent):
    B_grp = 'O+'
    _Age = 20

In [46]:
y = child()

In [47]:
y.B_grp

'O+'

In [48]:
y._Age

20

In [49]:
y.sir_name


'Smith'

In [50]:
y._city

40

In [51]:
class child2(child):
    venue = 'downtown'
    state = 'TG'

In [52]:
z = child2()

In [53]:
z.sir_name

'Smith'

In [54]:
class parent1:
    sir_name = 'smith'
    _city = 'hyd'

In [55]:
class mult(parent,parent1):
    age = 22

In [56]:
m = mult()

In [57]:
m.age

22

In [58]:
m.sir_name

'Smith'

In [59]:
m._city # city is there in both parent and parent1 but we mentioned parent first in attributes so parent's city will be printed

40

In [68]:
class Organisation:
    def __init__(self,name,noe,city):
        self.name = name
        self.noe = noe
        self.city = city
    def intro(self):
        print("welcome to our organisation")
    
class School(Organisation):
    def __init__(self,name,noe,city,nos):
        super().__init__(name,noe,city)
        self.nos = nos

In [66]:
o1 = Organisation("ABC",100,"HYD")


In [69]:
s1 = School('XYZ',20,'hyd',400)

In [70]:
s1.name

'XYZ'

In [71]:
o1.noe

100

In [72]:
class clg(School):
    def __init__(self,name,noe,city,nos,nob):
        super().__init__(name,noe,city,nos)
        self.nob = nob

In [73]:
c1 = clg('GNITS',30,'hyd',1000,7)

In [74]:
c1.name

'GNITS'

In [76]:
o1.name

'ABC'

In [77]:
s1.name

'XYZ'

In [78]:
c1.nob

7

In [ ]:
# multiple inheritance

In [81]:
class Organisation:
    def __init__(self,name,num_emp,city):
        self.name = name
        self.num_emp = num_emp
        self.city = city
class syllabus:
    def __init__(self,board):
        self.board=board
class School(Organisation,syllabus):
    def __init__(self,name,num_emp,city,board,num_stu):
        Organisation.__init__(self,name,num_emp,city)
        syllabus.__init__(self,board)
        self.num_stu=num_stu

In [ ]:
# mro - method resolution order , it shows order of classes

In [82]:
print(Organisation.mro())

[<class '__main__.Organisation'>, <class 'object'>]


In [83]:
print(School.mro())

[<class '__main__.School'>, <class '__main__.Organisation'>, <class '__main__.syllabus'>, <class 'object'>]


In [159]:
class cost:
    def __init__(self,name,age,sex,bmi,num_children,smoker,pay1):
        self.name =  name
        self.age = age
        self.sex= sex
        self.bmi = bmi
        self.num_children = num_children
        self.smoker = smoker
        self.pay1 = pay1
    def estimate(self):
        if self.smoker=="yes":
             self.pay1 = 20000+(0.25*20000)
        self.pay1 = self.pay1 + self.num_children*(0.25*20000)
        self.pay1 = self.pay1 + ((0.05)*20000)
        self.pay1 = self.pay1 + (0.10)*20000
        print("customer pay is:",self.pay1)
    def update_age(self,age):
        self.age = age
    def update_smoker(self,smoker):
        self.smoker = smoker
    def update_bmi(self,bmi):
        self.bmi = bmi
    def display_db(self):
        print("name: ",self.name)
        print("age:",self.age)
        print("sex:",self.sex)
        print("bmi:",self.bmi)
        print("num_children:",self.num_children)
        print("smoker?",self.smoker)
        print("pay:",self.pay1)
        cost.pay1 = 20000

In [160]:
c = cost("nik",30,"female",18.5,2,"no",20000)

In [161]:
c.estimate()

customer pay is: 33000.0


In [162]:
c.display_db()

name:  nik
age: 30
sex: female
bmi: 18.5
num_children: 2
smoker? no
pay: 33000.0


In [163]:
d =cost("bits",40,"male",19.5,3,"no",20000)

In [164]:
d.estimate()

customer pay is: 38000.0


In [165]:
d.display_db()

name:  bits
age: 40
sex: male
bmi: 19.5
num_children: 3
smoker? no
pay: 38000.0


In [166]:
c.display_db()
d.display_db()

name:  nik
age: 30
sex: female
bmi: 18.5
num_children: 2
smoker? no
pay: 33000.0
name:  bits
age: 40
sex: male
bmi: 19.5
num_children: 3
smoker? no
pay: 38000.0


In [167]:
# abstract methods
# polymorphism

In [168]:
from abc import ABC, abstractmethod

In [172]:
class car(ABC):
    @abstractmethod
    def mileage(self):
        pass
    @abstractmethod
    def manufac(self):
        pass
class sports(car):
    def mileage(self):
        print("the mileage of the car is 15 kms")
    def manufac(self):
        print("the car is manufactured in hyd")
class economy(car):
    def mileage(self):
        print("the milage of the car is 25kms")
    def manufac(self):
        print("the car is manufactured in bangalore")

In [ ]:
#magic methods

In [203]:
class Record:
    def __init__(self,Title,Author,pages):
        self.Title = Title
        self.Author = Author
        self.pages = pages
    def __len__(self):  # len is a magic method and we are making it to behave the way we want 
        return self.pages

    def __str__(self):# str is a mag ic method and we are making it to behave the way we want
        return "The {} is written by {}".format(self.Title,self.Author)
    def __del__(self):
        # del is a magic method and we are making it to behave the way we want
         return ("the book is deleted")

In [205]:
b3 = Record("My python","US",100)


the book is deleted


In [206]:
str(b2)

'The My python is written by US'

In [197]:
len(b2)

100

In [198]:
del(b2)

the book is deleted


In [212]:
b6 = Record("My python","US",100)

# 20-10-22

In [1]:
# numpy--> numerical analysis
# pandas--> data manipulation & analytics library
# scipy --> statistical library


# numpy

In [2]:
# numpy - ndiamensional arrays

In [3]:
import numpy as np

In [4]:
a1 = np.array([1,2,3,4])

In [5]:
a2 = np.array([11,22,33,44])

In [6]:
a1.shape

(4,)

In [7]:
a2.shape # 4 rows 1 col

(4,)

In [10]:
a2 = a2.reshape(2,2)

In [11]:
a2

array([[11, 22],
       [33, 44]])

In [12]:
a1.shape

(4,)

In [13]:
a2.shape

(2, 2)

In [14]:
type(a1)

numpy.ndarray

In [15]:
type(a2)

numpy.ndarray

In [19]:
arr = np.array([10,20,30,40,50,60]).reshape(2,3)

In [62]:
arr

array([[10, 20, 30],
       [80, 50, 40],
       [12, 16,  8]])

# traversing

In [22]:
arr[1,:]

array([40, 50, 60])

In [23]:
arr = np.array([[10,20,30,80,50,40,12,16,8]]).reshape(3,3)

In [24]:
arr

array([[10, 20, 30],
       [80, 50, 40],
       [12, 16,  8]])

In [30]:
arr[[0,2],::2]

array([[10, 30],
       [12,  8]])

In [31]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [33]:
arr.cumprod()

array([         10,         200,        6000,      480000,    24000000,
         960000000, -1364901888,  -363593728,  1386217472], dtype=int32)

In [34]:
arr.cumsum()

array([ 10,  30,  60, 140, 190, 230, 242, 258, 266], dtype=int32)

In [35]:
arr.T

array([[10, 80, 12],
       [20, 50, 16],
       [30, 40,  8]])

In [63]:
arr.flatten()

array([10, 20, 30, 80, 50, 40, 12, 16,  8])

In [64]:
np.vstack(arr)

array([[10, 20, 30],
       [80, 50, 40],
       [12, 16,  8]])

# subsetting

In [38]:
arr[arr>25] # subsetting
    

array([30, 80, 50, 40])

In [44]:
arr[(arr>25) & (arr<50)]

array([30, 40])

In [46]:
np.random.rand(10)

array([0.59858117, 0.00960011, 0.78196687, 0.49851376, 0.13583911,
       0.45632559, 0.88360956, 0.06092292, 0.96274866, 0.71780229])

In [49]:
np.random.randint(5,10,3) # 5 include , 10 exclude

array([8, 5, 9])

In [50]:
np.random.randn(10) 

array([-1.37107056,  0.23342091,  2.32996989,  0.89000165,  0.04286812,
       -0.4917179 ,  1.32784643,  0.474107  ,  0.03774339, -0.75803556])

# pandas

In [52]:
#pandas is aka data manipulation, analytic tool

In [53]:
import pandas as pd

In [54]:
#series - one diamension-one row/one col

In [56]:
s = pd.Series([10,20,15,25]) 

In [57]:
s

0    10
1    20
2    15
3    25
dtype: int64

In [58]:
# we can hv own index also as well as default 0,1,2.....indexing

In [65]:
s1 = pd.Series([100,200,300,400],index=['Mon','Tue','wed','thu'])

In [66]:
date = pd.date_range('20221020',periods=4,freq = '3M')

In [67]:
s2 = pd.Series([100,200,300,400],index=date)

In [69]:
help(pd.date_range)

Help on function date_range in module pandas.core.indexes.datetimes:

date_range(start=None, end=None, periods=None, freq=None, tz=None, normalize: 'bool' = False, name: 'Hashable' = None, closed=None, **kwargs) -> 'DatetimeIndex'
    Return a fixed frequency DatetimeIndex.
    
    Returns the range of equally spaced time points (where the difference between any
    two adjacent points is specified by the given frequency) such that they all
    satisfy `start <[=] x <[=] end`, where the first one and the last one are, resp.,
    the first and last time points in that range that fall on the boundary of ``freq``
    (if given as a frequency string) or that are valid for ``freq`` (if given as a
    :class:`pandas.tseries.offsets.DateOffset`). (If exactly one of ``start``,
    ``end``, or ``freq`` is *not* specified, this missing parameter can be computed
    given ``periods``, the number of timesteps in the range. See the note below.)
    
    Parameters
    ----------
    start : str or

In [70]:
s2

2022-10-31    100
2023-01-31    200
2023-04-30    300
2023-07-31    400
Freq: 3M, dtype: int64

In [60]:
s1[0]

100

In [61]:
s1['Mon']

100

# data frames 

In [71]:
df = pd.DataFrame(np.random.randn(3,4))

In [72]:
df

0         1         2         3
0 -0.191962 -0.251075  0.991324  1.387186
1  1.110143  1.096075  0.973215  1.184222
2 -2.084064 -0.381678  1.318842  0.005531

In [73]:
df = pd.DataFrame(np.random.randn(3,4),columns=['a','b','c','d'])

In [74]:
df

a         b         c         d
0 -2.086936 -0.644357 -1.458664  1.361233
1 -0.030090 -0.089925 -0.734126  0.445243
2  0.264815  0.893757  1.518843 -0.668536

In [77]:
df = pd.DataFrame(np.random.randn(3,4),index = ['mon','tue','wed','thu','fri'],columns=['a','b','c','d'])

ValueError: Shape of passed values is (3, 4), indices imply (5, 4)

In [120]:
df = pd.DataFrame({'Day':['Mon','Tue','Wed','Thu','Fri'],'Temp':[12,16,22,25,21],'Rained?':['No','yes','No','Yes','no']})

In [121]:
# indexing
#[]-->access columns by label and then index for rows
#loc --> Access data purely by labels ( attribute names)
#iloc --> pure integer based indexing


In [122]:
df

Day  Temp Rained?
0  Mon    12      No
1  Tue    16     yes
2  Wed    22      No
3  Thu    25     Yes
4  Fri    21      no

In [123]:
df['Day']

0    Mon
1    Tue
2    Wed
3    Thu
4    Fri
Name: Day, dtype: object

In [124]:
df[['Day','Temp']]

Day  Temp
0  Mon    12
1  Tue    16
2  Wed    22
3  Thu    25
4  Fri    21

In [125]:
#row followed by column or column follwed by row anything will work but row u cant access like df[0] , instead u should do like df[0,1]

In [126]:
df[0:1]

Day  Temp Rained?
0  Mon    12      No

In [127]:
df['Day'][[0,3]]

0    Mon
3    Thu
Name: Day, dtype: object

In [128]:
df.loc[1]['Day']

'Tue'

In [129]:
df.loc[1][['Day','Rained?']]

Day        Tue
Rained?    yes
Name: 1, dtype: object

In [130]:
df.iloc[[1,4],::2]

Day Rained?
1  Tue     yes
4  Fri      no

In [141]:
df['cloud']=['yes','yes','no','yes','no']

In [132]:
df


Day  Temp Rained? cloud
0  Mon    12      No   yes
1  Tue    16     yes   yes
2  Wed    22      No    no
3  Thu    25     Yes   yes
4  Fri    21      no    no

In [133]:
df.insert(2,"c1",[0,1,0,1,0])df

In [134]:
df

Day  Temp  c1 Rained? cloud
0  Mon    12   0      No   yes
1  Tue    16   1     yes   yes
2  Wed    22   0      No    no
3  Thu    25   1     Yes   yes
4  Fri    21   0      no    no

In [136]:
df.drop('cloud',axis = 1,inplace=True) # axis=0 means cloud is a row name , axis = 1 means cloud is a col name, inplace means rechecking if its real that we want to drop or not

In [138]:
df

Day  Temp  c1 Rained?
0  Mon    12   0      No
1  Tue    16   1     yes
2  Wed    22   0      No
3  Thu    25   1     Yes
4  Fri    21   0      no

In [139]:
df[df['Rained?'].str.lower()=='yes']

Day  Temp  c1 Rained?
1  Tue    16   1     yes
3  Thu    25   1     Yes

In [140]:
df[(df['Rained?'].str.lower()=='yes') & (df['Temp']>20)]

Day  Temp  c1 Rained?
3  Thu    25   1     Yes

In [142]:
df['cloud'].unique()

array(['yes', 'no'], dtype=object)

In [144]:
df['cloud'].nunique() # number of unique

2

In [143]:
df['cloud'].value_counts()

yes    3
no     2
Name: cloud, dtype: int64

In [149]:
date=pd.date_range('20221020',periods=6,freq='M')

In [151]:
stock = pd.DataFrame(np.random.randn(6,4),columns=['open_price','close_price','high','low'], index=date)

In [152]:
stock

open_price  close_price      high       low
2022-10-31    0.860401    -1.440624 -0.465086  1.516506
2022-11-30    0.850869     0.253800 -0.635767  1.566524
2022-12-31   -0.659039    -1.769518  0.013293 -0.323985
2023-01-31   -1.188212    -1.654645  0.021894 -1.751822
2023-02-28    0.925626    -0.326075  0.678010  0.794352
2023-03-31   -1.453000     1.191693 -0.185041 -0.574296

In [156]:
stock.index

DatetimeIndex(['2022-10-31', '2022-11-30', '2022-12-31', '2023-01-31',
               '2023-02-28', '2023-03-31'],
              dtype='datetime64[ns]', freq='M')

In [157]:
stock.sort_index(ascending=False)

open_price  close_price      high       low
2023-03-31   -1.453000     1.191693 -0.185041 -0.574296
2023-02-28    0.925626    -0.326075  0.678010  0.794352
2023-01-31   -1.188212    -1.654645  0.021894 -1.751822
2022-12-31   -0.659039    -1.769518  0.013293 -0.323985
2022-11-30    0.850869     0.253800 -0.635767  1.566524
2022-10-31    0.860401    -1.440624 -0.465086  1.516506

In [158]:
stock.sort_values(by="high")

open_price  close_price      high       low
2022-11-30    0.850869     0.253800 -0.635767  1.566524
2022-10-31    0.860401    -1.440624 -0.465086  1.516506
2023-03-31   -1.453000     1.191693 -0.185041 -0.574296
2022-12-31   -0.659039    -1.769518  0.013293 -0.323985
2023-01-31   -1.188212    -1.654645  0.021894 -1.751822
2023-02-28    0.925626    -0.326075  0.678010  0.794352

In [159]:
index = ['FireFox','Chrome','Safari','IE10','Konqueror']


In [162]:
df = pd.DataFrame({'http_status':[200,200,404,404,301],'response_time':[0.04,0.02,0.07,0.08,1.0]},index = index)

In [163]:
new_index = ['safari','Iceweasel','Comodo Dragon','IE10','Chrome']

In [164]:
df.reindex(new_index)

http_status  response_time
safari                 NaN            NaN
Iceweasel              NaN            NaN
Comodo Dragon          NaN            NaN
IE10                 404.0           0.08
Chrome               200.0           0.02

In [ ]:
help(pd.MultiIndex)

In [166]:
# exploratory data analytics

In [ ]:
# Data Dictionary
# Exploring the data & find out need for clean
# insi